language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ktryber/react-test -f ./client/dev.Dockerfile ./client

script:
  - docker run -e CI=true ktryber/react-test npm test

after_success:
  - docker build -t ktryber/multi-client ./client
  - docker build -t ktryber/multi-nginx ./nginx
  - docker build -t ktryber/multi-server ./server
  - docker build -t ktryber/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push ktryber/multi-client
  - docker push ktryber/multi-nginx
  - docker push ktryber/multi-server
  - docker push ktryber/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-566654164382
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
